language:
- cpp

cache:
  bundler: true
  timeout: 1000 #seconds
  directories:
  - "${TRAVIS_BUILD_DIR}/../mxe/"

matrix:
  include:
  # linux with gcc default (4.8)
  - os: linux
    dist: trusty
    compiler: gcc

before_install:
- sudo apt-get -qq update

install:
- .ci/install-deps.sh

before_script:
- 'export CACHE_DIR="${TRAVIS_BUILD_DIR}/../mxe"'
- 'export PAGES_OUT="${TRAVIS_BUILD_DIR}/../pages_out"'
- ls -l "${CACHE_DIR}"
- .ci/handle_cache.sh
- du -hs .

script:
#- echo "nothing to do"
- jack2/make.sh
- fastdb/make.sh

after_script:

before_cache:
  - ls -l "${CACHE_DIR}"

after_success:
- shout "success"

after_failure:
- shout "fail"

before_deploy:
- mkdir -p "${PAGES_OUT}"
- ls -ltr "${PAGES_OUT}"

deploy:
  provider: pages
  local-dir: "${PAGES_OUT}"
  skip-cleanup: true
  keep-history: true
  github-token: "${FOO_BAR}"
  repo: 7890/mxe_deploy
  target-branch: master
  on:
    branch: master
#    condition: false

after_deploy:
- shout "deployed"

branches:
  only:
    - /.*/

notifications:
  email: false

