language:
  - cpp

cache:
  bundler: true
  timeout: 1000 #seconds
  directories:
    - "${TRAVIS_BUILD_DIR}/../mxe/"

matrix:
  include:
    # linux with gcc default (4.8)
    - os: linux
      dist: trusty
      compiler: gcc

before_install:
  - sudo apt-get -qq update

install:
  - .ci/install-deps.sh

before_script:
  - ls -l "${TRAVIS_BUILD_DIR}/../mxe/"
  - .ci/handle_cache.sh

script:
  - echo "nothing to do"
#  - jack2/make.sh
#  - fastdb/make.sh

after_script:

before_cache:
  - ls -l "${TRAVIS_BUILD_DIR}/../mxe/"

after_success:
  - echo "build was successful. fantastic!"

after_failure:
  - echo "build failed. not lucky today."

before_deploy:
  - mkdir -p "${TRAVIS_BUILD_DIR}/../pages_out"

deploy:
  provider: pages
  local-dir: "${TRAVIS_BUILD_DIR}/../pages_out"
  skip-cleanup: true
  keep-history: true
  github-token: "${FOO_BAR}"
  repo: 7890/mxe_deploy
  target-branch: master
  on:
    branch: master
    condition: false

after_deploy:
  - ARTIFACT_FILE=$(ls -1tr "${TRAVIS_BUILD_DIR}/../pages_out" | tail -1)
  - echo "${ARTIFACT_FILE}"

branches:
  only:
    - /.*/

notifications:
  email: false

